FROM python:3.8.3-alpine

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# set work directory
# install dependencies
WORKDIR /requirements
COPY requirements /requirements
RUN pip install --upgrade pip
RUN pip install -r dev.txt
WORKDIR /app